[build]
  command = "npm install --legacy-peer-deps --verbose && npm run build"
  publish = "dist"
  NODE_VERSION = "20.11.1"
  NODE_ENV = "production"
  NETLIFY_BUILD_DEBUG = "true"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 