[build]
  command = "npm install --ignore-scripts && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
  GO_VERSION = "1.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 