[build]
  command = "npm install && npm run build"
  publish = "dist"
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 